--- 
title: "The Influence of Inclusion on Attendance"
author: "Katherine Wilson, Wendy Chan, Michael Gottfried"
date: "`r Sys.Date()`"
subtitle: A Matched Comparison Study of NYC Public Schools
site: bookdown::bookdown_site
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Abstract


As researchers begin to better understand classroom level interventions that improve student outcomes, many are curious about a new question: what school level factors might also influence student outcomes? One school level factor of interest are “class options”, or the ways that students are organized in classrooms according to ability level. Here, we focus specifically on one historically contentious class option for students with disabilities: the self-contained class. Our focus is New York City, the largest school district in the country, where class options vary widely across public schools. A majority of schools have a self-contained class option, where students with disabilities (SWD) are educated in a separate classroom, away from their gen-ed peers. Other schools have no self-contained option, and SWD are educated along with their gen-ed peers, with necessary in-class support and pull-out services. In this study, we explore whether such a visible, detached, class option might affect attendance rates for both SWD and for gen-ed students. We find that in schools with full inclusion models, where SWD learn alongside students without disabilities, chronic absenteeism for all students decreases. We theorize that the effect is due to a greater sense of belonging with the school community that inclusion fosters. Using rigorous causal inference methods with a nuanced treatment of the propensity score to identify heterogeneous treatment effects, particularly among low-income schools, we match 1,125 NYC public schools on key covariates to identify the effect of inclusion on school attendance.

